In [47]:

import pyodbc
import pandas as pd

server = 'CORSA-SRV\CORSADB'
database = 'CORSA'
user = 'saint'
pwd = 'Clave.Saint'
cnnstr = 'DRIVER={ODBC Driver 17 for SQL Server};SERVER=' + server + ';DATABASE=' + database +';UID=' + user + ';PWD=' + pwd

conn = pyodbc.connect(cnnstr)
cursor = conn.cursor()
# query = 'select * from MAECXP WHERE CLI_NOMBRE like \'%MPS%\' OR CLI_NOMBRE LIKE \'IMPRESISTEM%\''
query = '''SELECT MAECXP.CLI_NOMBRE, inventariogeneral.* 
FROM inventariogeneral LEFT JOIN MAECXP ON inventariogeneral.INV_PROVEE = MAECXP.CLI_CEDULA 
ORDER BY INV_SALACT DESC, MAECXP.CLI_NOMBRE ASC'''


df = pd.read_sql(query, conn)

In [48]:
df.dtypes

CLI_NOMBRE            object
INV_CLASE             object
INV_GRUPO             object
INV_LINEA             object
INV_PROVEE            object
INV_REFER             object
INV_NOMBRE            object
INV_UNDMED            object
INV_CODIGO            object
INV_ULTMOV    datetime64[ns]
INV_ACTIVO              bool
INV_PROMOC              bool
INV_BODEGA            object
INV_MARCA             object
INV_MODELO            object
INV_UBICA             object
INV_LOTE              object
INV_VALCOM           float64
INV_PREVEN           float64
INV_PORCEN           float64
INV_CANANT           float64
INV_VALANT           float64
INV_CANENT           float64
INV_VALENT           float64
INV_CANSAL           float64
INV_VALSAL           float64
INV_SALACT           float64
INV_VALACT           float64
dtype: object

In [49]:
df.describe(include="all")

,INV_VALCOM,INV_PREVEN,INV_PORCEN,INV_CANANT,INV_VALANT,INV_CANENT,INV_VALENT,INV_CANSAL,INV_VALSAL,INV_SALACT,INV_VALACT
count,1.670600e+04,1.670600e+04,16706.000000,16706.000000,1.670600e+04,16706.0,16706.0,16706.000000,16706.000000,16706.000000,1.670600e+04
mean,6.576710e+04,2.743970e+05,19.204418,50.103983,1.591623e+05,0.0,0.0,0.006165,108.614254,50.097818,1.590537e+05
std,3.154477e+05,2.259727e+07,5.809419,1615.953026,1.063430e+06,0.0,0.0,0.269620,7390.762552,1615.950803,1.063001e+06
min,-9.750000e+03,0.000000e+00,0.000000,-45.000000,-7.126200e+07,0.0,0.0,0.000000,0.000000,-45.000000,-7.126200e+07
25%,1.560000e+03,2.700000e+03,20.000000,1.000000,8.125000e+03,0.0,0.0,0.000000,0.000000,1.000000,8.125000e+03
50%,6.281000e+03,1.080000e+04,20.000000,3.000000,2.778445e+04,0.0,0.0,0.000000,0.000000,3.000000,2.776768e+04
75%,2.924475e+04,4.760000e+04,20.000000,10.000000,9.179118e+04,0.0,0.0,0.000000,0.000000,10.000000,9.176582e+04
max,2.490650e+07,2.920158e+09,250.000000,168400.000000,5.843454e+07,0.0,0.0,24.000000,661296.000000,168400.000000,5.843454e+07

In [25]:
df.tail(10)

,CLI_NOMBRE,INV_CLASE,INV_GRUPO,INV_LINEA,INV_PROVEE,INV_REFER,INV_NOMBRE,INV_UNDMED,INV_CODIGO,INV_ULTMOV,...,INV_PREVEN,INV_PORCEN,INV_CANANT,INV_VALANT,INV_CANENT,INV_VALENT,INV_CANSAL,INV_VALSAL,INV_SALACT,INV_VALACT
176,SED INTERNACIONAL DE COLOMBIA S.A.S,50,5100,514,830036108,514HPK0047,HPE USB US KEYBOARD/MOUSE KIT 631341-B21,Und,,2019-11-27,...,79800.0,15.0,1.0,5.795460e+04,0.0,0.0,0.0,0.0,1.0,5.795460e+04
177,SED INTERNACIONAL DE COLOMBIA S.A.S,50,5100,511,830036108,511HPK0780,COMP PC HP 280 G5 1R2K2LA#ABM,Und,,2021-08-02,...,1632600.0,15.0,1.0,1.435027e+06,0.0,0.0,0.0,0.0,1.0,1.435027e+06
178,SED INTERNACIONAL DE COLOMBIA S.A.S,50,5100,513,830036108,513HPK0490,COMP SERVIDOR HP PROLIANT ML30 G9 831064-001,UND,513HPK0490,2018-08-02,...,1687800.0,20.0,1.0,1.248072e+06,0.0,0.0,0.0,0.0,1.0,1.248072e+06
179,SED INTERNACIONAL DE COLOMBIA S.A.S,50,5100,512,830036108,512HPK0880,COMP PORTATIL HP 240 G7 151D5LT#ABM,Und,,2021-07-27,...,1589800.0,15.0,1.0,1.399000e+06,0.0,0.0,0.0,0.0,1.0,1.399000e+06
180,SED INTERNACIONAL DE COLOMBIA S.A.S,50,5100,512,830036108,512HPK0880,COMP PORTATIL HP 240 G7 151D5LT#ABM,Und,,2021-07-27,...,1589800.0,15.0,1.0,1.399000e+06,0.0,0.0,0.0,0.0,1.0,1.399000e+06
181,SED INTERNACIONAL DE COLOMBIA S.A.S,50,5100,512,830036108,512HPK0880,COMP PORTATIL HP 240 G7 151D5LT#ABM,Und,,2021-07-27,...,1589800.0,15.0,1.0,1.399000e+06,0.0,0.0,0.0,0.0,1.0,1.399000e+06
182,SED INTERNACIONAL DE COLOMBIA S.A.S,50,5400,541,830036108,541HPK0777,ESCANER HP SCANJET SJ 4500FN1 L2749A,Und,541HPK0777,2021-04-22,...,3604000.0,20.0,1.0,2.450000e+06,0.0,0.0,0.0,0.0,1.0,2.450000e+06
183,SED INTERNACIONAL DE COLOMBIA S.A.S,50,5400,545,830036108,545HPK0013,IMPRESORA HP DESIGNJET T130 24 PULG. 5ZY58A#B1K,Und,,2020-08-28,...,3108300.0,15.0,1.0,1.930810e+06,0.0,0.0,0.0,0.0,1.0,1.930810e+06
184,SUMINISTROS E IMPRESOS S.A.S.,20,2400,243,860523795,243HPK0453,TONER P/IMP HP CF230A NEGRO,Und,,2021-08-27,...,375700.0,20.0,1.0,2.080000e+05,0.0,0.0,0.0,0.0,1.0,2.080000e+05
185,SUMINISTROS E IMPRESOS S.A.S.,24,2400,242,860523795,242HPK1045,CARTUCHO P/IMP. HP CZ105AL #662XL NEGRO CZ105AL,UND,886112670139,2021-08-30,...,129300.0,20.0,1.0,7.500000e+04,0.0,0.0,0.0,0.0,1.0,7.500000e+04

In [46]:

# df.index
# df.columns
rows = df.to_numpy()
df.T
df.sort_values(by='INV_REFER')
skus = df.loc[:, ['CLI_NOMBRE','INV_NOMBRE', 'INV_SALACT']]
skus.describe(include="all")

,CLI_NOMBRE,INV_NOMBRE,INV_SALACT
count,115,186,186.000000
unique,14,164,NaN
top,IMPRESISTEM S.A.S.,"MONITOR HP 19.5"" LED HP V201 E6W38AA E6W38AA",NaN
freq,49,8,NaN
mean,NaN,NaN,3.467742
std,NaN,NaN,5.880939
min,NaN,NaN,1.000000
25%,NaN,NaN,1.000000
50%,NaN,NaN,1.000000
75%,NaN,NaN,3.000000
max,NaN,NaN,56.000000